export const displayCountry = (country: string) => {
    const emojis: Record<string, string> = {
        "Sweden": "🇸🇪",
        "Israel": "🇮🇱",
        "Czechia": "🇨🇿",
        "Norway": "🇳🇴",
        "Finland": "🇫🇮",
        "Latvia": "🇱🇻",
        "Switzerland": "🇨🇭",
        "Spain": "🇪🇸",
        "Italy": "🇮🇹",
        "United Kingdom": "🇬🇧",
        "Japan": "🇯🇵",
        "Belgium": "🇧🇪",
        "Turkey": "🇹🇷",
        "Austria": "🇦🇹",
        "Bulgaria": "🇧🇬",
        "Hungary": "🇭🇺",
        "United States": "🇺🇸",
        "Australia": "🇦🇺",
        "Germany": "🇩🇪",
        "France": "🇫🇷",
        "Romania": "🇷🇴",
        "Denmark": "🇩🇰",
        "Poland": "🇵🇱",
        "Estonia": "🇪🇪",
        "Slovenia": "🇸🇮",
        "Ukraine": "🇺🇦",
        "Canada": "🇨🇦",
        "Indonesia": "🇮🇩",
        "Portugal": "🇵🇹",
        "Greenland": "🇬🇱",
        "New Zealand": "🇳🇿",
        "Belarus": "🇧🇾",
        "Moldova": "🇲🇩",
        "China": "🇨🇳",
        "Lithuania": "🇱🇹",
        "North Macedonia": "🇲🇰",
        "Netherlands": "🇳🇱",
        "Slovakia": "🇸🇰",
        "Taiwan, Province of China": "🇹🇼",
        "Iceland": "🇮🇸",
        "Serbia": "🇷🇸",
        "Hong Kong": "🇭🇰",
        "Ireland": "🇮🇪",
        "Russian Federation": "🇷🇺",
        "Colombia": "🇨🇴",
        "Luxembourg": "🇱🇺",
        "Croatia": "🇭🇷",
        "South Korea": "🇰🇷",
        "Georgia": "🇬🇪",
        "Mauritius": "🇲🇺",
        "Ecuador": "🇪🇨",
        "Brazil": "🇧🇷",
        "Thailand": "🇹🇭",
        "Bahrain": "🇧🇭",
        "Malaysia": "🇲🇾",
        "Morocco": "🇲🇦",
        "Dominica": "🇩🇲",
        "Saint Helena": "🇸🇭",
        "Antigua and Barbuda": "🇦🇬",
        "Saint Kitts and Nevis": "🇰🇳",
        "Puerto Rico": "🇵🇷",
        "Bosnia and Herzegovina": "🇧🇦",
        "South Africa": "🇿🇦",
        "Faroe Islands": "🇫🇴",
        "Andorra": "🇦🇩",
        "Kazakhstan": "🇰🇿"
    };
    
    const emoji = emojis[country];

    const shortCountryNames: Record<string, string> = {
        "United States": "USA",
        "United Kingdom": "UK",
        "South Korea": "Korea",
        "Russian Federation": "Russia",
        "Taiwan, Province of China": "Taiwan",
        "Bosnia and Herzegovina": "Herzegovina",
        "Saint Kitts and Nevis": "St. Kitts",
        "Saint Helena": "St. Helena",
        "Antigua and Barbuda": "Antigua",
    }

    return `${emoji ? emoji + ' ' : ''}${shortCountryNames[country] || country}`;
}
